name: Build and Deploy
on:
  push:
    branches:
      - main 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: main  # The branch the action should deploy to.
        FOLDER: Frontend  # The folder the action should deploy.
        CLEAN: true  # Automatically remove deleted files from the deployment.
